# Generated by Django 4.2.3 on 2023-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
